# Config file for CelebA dataset (200k)

output_dir: 'output/'
structure: 'linear'
device_id: ('0')
checkpoint_factor: 4
feedback_factor: 4
dataset:
  img_dir: '/var/scratch/mms496/data/ffhq/full/thumbnails128x128'
  folder: True
  resolution: 128
sched:
  epochs: [8,16,32,32,64,64]
