# Config file for CelebA dataset (200k)

output_dir: '/content/output/mnist'
structure: 'fixed'
device_id: ('0')
use_ema: False
checkpoint_factor: 0
feedback_factor: 20
num_samples: 64
dataset:
  img_dir: '/content/drive/MyDrive/datasets/mnist/training'
  folder: True
  resolution: 32
  channels: 1
sched:
  epochs: [8,16,32,32,64,300]

