# Config file for CelebA dataset (200k)

output_dir: '/home/mms496/StyleVAE_Experiments/stylegan/output/'
structure: 'linear'
device_id: ('0')
checkpoint_factor: 1
feedback_factor: 1
dataset:
  img_dir: '/var/scratch/mms496/data/ffhq/partial/thumbnails128x128'
  folder: True
  resolution: 128
sched:
  epochs: [8,16,32,32,64,300]
