# Config file for CelebA dataset (200k)

output_dir: '/content/output/ffhq'
structure: 'linear'
device_id: ('0')
use_ema: False
checkpoint_factor: 1
feedback_factor: 2
dataset:
  img_dir: '/content/drive/MyDrive/datasets/ffhq'
  folder: True
  resolution: 128
sched:
  epochs: [8,16,32,32,64,300]
